# Generated by Django 4.1.7 on 2023-03-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='text',
        ),
    ]
